# Config file for automatic testing at travis-ci.org

language: python

sudo: false

matrix:
  include:
    - python: 3.5
      env: TOX_ENV='flake8'
    #- python: 3.5
    #  env: TOX_ENV='isort' FIXME: For isort to pass the following changes need to be ported to this support/4.0.x branch:
    #                       https://github.com/divio/djangocms-text-ckeditor/commit/a6069096fdac80931fd328055d1d615d168c33df
      # Django 1.11
    - python: 3.5
      env: DJANGO='dj111' CMS='cms40' FE=1
    # Django 2.1
    - python: 3.6
      env: DJANGO='dj21' CMS='cms40' FE=1
    # Django 2.2
    - python: 3.6
      env: DJANGO='dj22' CMS='cms40' FE=1
    - python: 3.7
      env: DJANGO='dj22' CMS='cms40' FE=1
      dist: xenial
      sudo: true
    - python: 3.8
      env: DJANGO='dj22' CMS='cms40'

before_script:
  - pip install coverage isort tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"
  - if [ "$FE" == 1 ]; then nvm install 8 && nvm use 8; fi
  - if [ "$FE" == 1 ]; then npm config set spin false; fi
  - if [ "$FE" == 1 ]; then npm install -g npm; fi
  - if [ "$FE" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FE" == 1 ]; then npm install -g codeclimate-test-reporter; fi
  - if [ "$FE" == 1 ]; then npm ci; fi

install:
  - pip install -U tox>=1.8 coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"
  - "if [[ $FE == 1 ]]; then export FE_STR='-fe'; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
